import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { PlusIcon } from 'lucide-react'
import { createChannel, listChannels, listPlaybooks, updateChannel } from '@/api'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardAction, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Field, FieldGroup, FieldLabel } from '@/components/ui/field'
import { Input } from '@/components/ui/input'
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle, SheetTrigger } from '@/components/ui/sheet'
import { Spinner } from '@/components/ui/spinner'

export function ChannelsPage(){const client=useQueryClient();const channels=useQuery({queryKey:['channels'],queryFn:listChannels});const playbooks=useQuery({queryKey:['playbooks'],queryFn:listPlaybooks});const [open,setOpen]=useState(false);const [address,setAddress]=useState('test-'+Date.now());const defaultPB=playbooks.data?.playbooks[0]?.id??'';const create=useMutation({mutationFn:()=>createChannel({kind:'dev',address,defaultPlaybookId:defaultPB}),onSuccess:()=>{client.invalidateQueries({queryKey:['channels']});setOpen(false)}});const route=useMutation({mutationFn:({connection,id}:{connection:NonNullable<typeof channels.data>['connections'][number];id:string})=>updateChannel(connection,id),onSuccess:()=>client.invalidateQueries({queryKey:['channels']})});return <section className="flex flex-col gap-5"><div className="flex items-start gap-3"><div><h2 className="font-heading text-xl font-semibold">Channels</h2><p className="text-sm text-muted-foreground">Route each connection to one of the organization&apos;s playbooks.</p></div><Sheet open={open} onOpenChange={setOpen}><SheetTrigger render={<Button className="ml-auto" size="sm"/>}><PlusIcon data-icon="inline-start"/>Add test connection</SheetTrigger><SheetContent><SheetHeader><SheetTitle>Add test connection</SheetTitle><SheetDescription>Create another dev simulator endpoint for testing playbook routing.</SheetDescription></SheetHeader><div className="p-4"><FieldGroup><Field><FieldLabel htmlFor="channel-address">Address</FieldLabel><Input id="channel-address" value={address} onChange={e=>setAddress(e.target.value)}/></Field></FieldGroup></div><SheetFooter><Button disabled={!address||!defaultPB||create.isPending} onClick={()=>create.mutate()}>{create.isPending&&<Spinner data-icon="inline-start"/>}Create</Button></SheetFooter></SheetContent></Sheet></div>
  <div className="grid gap-3 md:grid-cols-2">{channels.data?.connections.map(connection=><Card key={connection.id}><CardHeader><CardTitle>{connection.address}</CardTitle><CardDescription>{connection.kind} · {connection.status}</CardDescription><CardAction><Badge variant="secondary">v{connection.version}</Badge></CardAction></CardHeader><CardContent><Field><FieldLabel>Default playbook</FieldLabel><Select value={connection.default_playbook_id} onValueChange={value=>value&&route.mutate({connection,id:String(value)})}><SelectTrigger className="w-full"><SelectValue placeholder="Select a playbook"/></SelectTrigger><SelectContent><SelectGroup>{playbooks.data?.playbooks.map(pb=><SelectItem key={pb.id} value={pb.id}>{pb.name}</SelectItem>)}</SelectGroup></SelectContent></Select></Field></CardContent></Card>)}</div>
  <div><h3 className="mb-3 font-heading font-medium">Channel kinds</h3><div className="grid gap-3 md:grid-cols-2">{channels.data?.kinds.map(kind=><Card size="sm" key={kind.id}><CardHeader><CardTitle>{kind.label}</CardTitle><CardDescription>{kind.description}</CardDescription><CardAction><Badge variant={kind.status==='available'?'secondary':'outline'}>{kind.status==='available'?'Available':'Coming soon'}</Badge></CardAction></CardHeader></Card>)}</div></div></section>}
