import { useEffect, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { PlusIcon, Trash2Icon } from 'lucide-react'
import { getOrgProfile, type OrgProfile, updateOrgProfile } from '@/api'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card'
import { Field, FieldGroup, FieldLabel } from '@/components/ui/field'
import { Input } from '@/components/ui/input'
import { Spinner } from '@/components/ui/spinner'
import { Textarea } from '@/components/ui/textarea'

export function KnowledgePage(){const client=useQueryClient();const query=useQuery({queryKey:['org-profile'],queryFn:getOrgProfile});const [draft,setDraft]=useState<OrgProfile>();const [notice,setNotice]=useState('');useEffect(()=>{if(query.data)setDraft(structuredClone(query.data.profile))},[query.data]);const save=useMutation({mutationFn:()=>updateOrgProfile(draft!,query.data!.version),onSuccess:data=>{client.setQueryData(['org-profile'],data);setDraft(structuredClone(data.profile));setNotice('Knowledge saved.');},onError:error=>setNotice(error.message)});if(!draft||!query.data)return <Spinner/>;return <section className="flex flex-col gap-5"><div><h2 className="font-heading text-xl font-semibold">Knowledge</h2><p className="text-sm text-muted-foreground">The only operational facts the inquiry lane may state.</p></div><Card><CardHeader><CardTitle>Business profile</CardTitle><CardDescription>Shared across this organization&apos;s current and future playbooks.</CardDescription></CardHeader><CardContent><FieldGroup><Field><FieldLabel htmlFor="business-name">Business name</FieldLabel><Input id="business-name" value={draft.business_name} onChange={e=>setDraft({...draft,business_name:e.target.value})}/></Field><Field><FieldLabel htmlFor="hours">Hours</FieldLabel><Input id="hours" value={draft.hours} onChange={e=>setDraft({...draft,hours:e.target.value})}/></Field><Field><FieldLabel htmlFor="service-area">Service area</FieldLabel><Input id="service-area" value={draft.service_area} onChange={e=>setDraft({...draft,service_area:e.target.value})}/></Field></FieldGroup></CardContent></Card><Card><CardHeader><CardTitle>Facts</CardTitle><CardDescription>Short, explicit statements the agent can safely use in replies.</CardDescription></CardHeader><CardContent><FieldGroup>{draft.facts.map((fact,index)=><Field key={fact.id}><div className="flex gap-2"><Input aria-label="Fact label" value={fact.label} onChange={e=>setDraft({...draft,facts:draft.facts.map((f,i)=>i===index?{...f,label:e.target.value}:f)})}/><Button variant="ghost" size="icon-sm" aria-label="Remove fact" onClick={()=>setDraft({...draft,facts:draft.facts.filter((_,i)=>i!==index)})}><Trash2Icon/></Button></div><Textarea aria-label="Fact text" value={fact.text} onChange={e=>setDraft({...draft,facts:draft.facts.map((f,i)=>i===index?{...f,text:e.target.value}:f)})}/></Field>)}</FieldGroup></CardContent><CardFooter className="gap-3"><Button variant="outline" size="sm" onClick={()=>setDraft({...draft,facts:[...draft.facts,{id:crypto.randomUUID(),label:'',text:''}]})}><PlusIcon data-icon="inline-start"/>Add fact</Button></CardFooter></Card><div className="flex items-center gap-3"><Button disabled={save.isPending} onClick={()=>save.mutate()}>{save.isPending&&<Spinner data-icon="inline-start"/>}Save knowledge</Button>{notice&&<p className="text-sm text-muted-foreground">{notice}</p>}</div></section>}
